-- Bob's Used Bookstore Classic - PostgreSQL schema + seed script.
-- Engine counterpart of db-scripts/bobs-used-bookstore-classic-db.sql (SQL Server).
--
-- Type mapping (dual-db-port Appendix C):
--   nvarchar(max)   -> text
--   nvarchar(n)     -> varchar(n)
--   datetime        -> timestamp
--   decimal(18,2)   -> numeric(18,2)
--   bit             -> boolean
--   int IDENTITY    -> integer GENERATED BY DEFAULT AS IDENTITY
--   timestamp (rowversion) -> omitted: rowversion has no PostgreSQL equivalent and the
--     EF6 model leaves the RowVersion concurrency column unmapped on this engine
--     (see DUAL_DB_PORT_REPORT.md, "No equivalent" flags).
--
-- Identifier style: preserve (quoted PascalCase, schema public).
-- SQL Server's READ_COMMITTED_SNAPSHOT ON is native behavior on PostgreSQL
-- (MVCC snapshot reads); no database-level toggle is required.
--
-- Run against the target database, e.g.:
--   createdb "BookStoreClassic"
--   psql -d "BookStoreClassic" -f bobs-used-bookstore-classic-db-postgresql.sql

CREATE TABLE IF NOT EXISTS public."__MigrationHistory"(
	"MigrationId" varchar(150) NOT NULL,
	"ContextKey" varchar(300) NOT NULL,
	"Model" bytea NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK_dbo.__MigrationHistory" PRIMARY KEY ("MigrationId", "ContextKey")
);

CREATE TABLE IF NOT EXISTS public."Customer"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Sub" varchar(450) NULL,
	"Username" text NULL,
	"FirstName" text NULL,
	"LastName" text NULL,
	"Email" text NULL,
	"DateOfBirth" timestamp NULL,
	"Phone" text NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.Customer" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Address"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"AddressLine1" text NULL,
	"AddressLine2" text NULL,
	"City" text NULL,
	"State" text NULL,
	"Country" text NULL,
	"ZipCode" text NULL,
	"CustomerId" integer NOT NULL,
	"IsActive" boolean NOT NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.Address" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ReferenceData"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"DataType" integer NOT NULL,
	"Text" text NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.ReferenceData" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Book"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Name" text NULL,
	"Author" text NULL,
	"Year" integer NULL,
	"ISBN" text NULL,
	"PublisherId" integer NOT NULL,
	"BookTypeId" integer NOT NULL,
	"GenreId" integer NOT NULL,
	"ConditionId" integer NOT NULL,
	"CoverImageUrl" text NULL,
	"Summary" text NULL,
	"Price" numeric(18, 2) NOT NULL,
	"Quantity" integer NOT NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.Book" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Offer"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Author" text NULL,
	"ISBN" text NULL,
	"BookName" text NULL,
	"FrontUrl" text NULL,
	"GenreId" integer NOT NULL,
	"ConditionId" integer NOT NULL,
	"PublisherId" integer NOT NULL,
	"BookTypeId" integer NOT NULL,
	"Summary" text NULL,
	"OfferStatus" integer NOT NULL,
	"Comment" text NULL,
	"CustomerId" integer NOT NULL,
	"BookPrice" numeric(18, 2) NOT NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.Offer" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Order"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"CustomerId" integer NOT NULL,
	"AddressId" integer NOT NULL,
	"DeliveryDate" timestamp NOT NULL,
	"OrderStatus" integer NOT NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.Order" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."OrderItem"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"OrderId" integer NOT NULL,
	"BookId" integer NOT NULL,
	"Quantity" integer NOT NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.OrderItem" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ShoppingCart"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"CorrelationId" text NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.ShoppingCart" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ShoppingCartItem"(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"ShoppingCartId" integer NOT NULL,
	"BookId" integer NOT NULL,
	"Quantity" integer NOT NULL,
	"WantToBuy" boolean NOT NULL,
	"CreatedBy" text NULL,
	"CreatedOn" timestamp NOT NULL,
	"UpdatedOn" timestamp NOT NULL,
	CONSTRAINT "PK_dbo.ShoppingCartItem" PRIMARY KEY ("Id", "ShoppingCartId")
);

-- Indexes (FK lookup indexes + the unique Customer.Sub index from the SQL Server script).

CREATE INDEX IF NOT EXISTS "IX_CustomerId" ON public."Address" ("CustomerId");

CREATE INDEX IF NOT EXISTS "IX_BookTypeId" ON public."Book" ("BookTypeId");
CREATE INDEX IF NOT EXISTS "IX_ConditionId" ON public."Book" ("ConditionId");
CREATE INDEX IF NOT EXISTS "IX_GenreId" ON public."Book" ("GenreId");
CREATE INDEX IF NOT EXISTS "IX_PublisherId" ON public."Book" ("PublisherId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Sub" ON public."Customer" ("Sub");

CREATE INDEX IF NOT EXISTS "IX_BookTypeId" ON public."Offer" ("BookTypeId");
CREATE INDEX IF NOT EXISTS "IX_ConditionId" ON public."Offer" ("ConditionId");
CREATE INDEX IF NOT EXISTS "IX_CustomerId" ON public."Offer" ("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_GenreId" ON public."Offer" ("GenreId");
CREATE INDEX IF NOT EXISTS "IX_PublisherId" ON public."Offer" ("PublisherId");

CREATE INDEX IF NOT EXISTS "IX_AddressId" ON public."Order" ("AddressId");
CREATE INDEX IF NOT EXISTS "IX_CustomerId" ON public."Order" ("CustomerId");

CREATE INDEX IF NOT EXISTS "IX_BookId" ON public."OrderItem" ("BookId");
CREATE INDEX IF NOT EXISTS "IX_OrderId" ON public."OrderItem" ("OrderId");

CREATE INDEX IF NOT EXISTS "IX_BookId" ON public."ShoppingCartItem" ("BookId");
CREATE INDEX IF NOT EXISTS "IX_ShoppingCartId" ON public."ShoppingCartItem" ("ShoppingCartId");

-- Foreign keys: cascade rules mirrored from the SQL Server script.

ALTER TABLE public."Address" DROP CONSTRAINT IF EXISTS "FK_dbo.Address_dbo.Customer_CustomerId";
ALTER TABLE public."Address" ADD CONSTRAINT "FK_dbo.Address_dbo.Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customer" ("Id") ON DELETE CASCADE;

ALTER TABLE public."Book" DROP CONSTRAINT IF EXISTS "FK_dbo.Book_dbo.ReferenceData_BookTypeId";
ALTER TABLE public."Book" ADD CONSTRAINT "FK_dbo.Book_dbo.ReferenceData_BookTypeId" FOREIGN KEY ("BookTypeId") REFERENCES public."ReferenceData" ("Id");

ALTER TABLE public."Book" DROP CONSTRAINT IF EXISTS "FK_dbo.Book_dbo.ReferenceData_ConditionId";
ALTER TABLE public."Book" ADD CONSTRAINT "FK_dbo.Book_dbo.ReferenceData_ConditionId" FOREIGN KEY ("ConditionId") REFERENCES public."ReferenceData" ("Id");

ALTER TABLE public."Book" DROP CONSTRAINT IF EXISTS "FK_dbo.Book_dbo.ReferenceData_GenreId";
ALTER TABLE public."Book" ADD CONSTRAINT "FK_dbo.Book_dbo.ReferenceData_GenreId" FOREIGN KEY ("GenreId") REFERENCES public."ReferenceData" ("Id");

ALTER TABLE public."Book" DROP CONSTRAINT IF EXISTS "FK_dbo.Book_dbo.ReferenceData_PublisherId";
ALTER TABLE public."Book" ADD CONSTRAINT "FK_dbo.Book_dbo.ReferenceData_PublisherId" FOREIGN KEY ("PublisherId") REFERENCES public."ReferenceData" ("Id");

ALTER TABLE public."Offer" DROP CONSTRAINT IF EXISTS "FK_dbo.Offer_dbo.Customer_CustomerId";
ALTER TABLE public."Offer" ADD CONSTRAINT "FK_dbo.Offer_dbo.Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customer" ("Id") ON DELETE CASCADE;

ALTER TABLE public."Offer" DROP CONSTRAINT IF EXISTS "FK_dbo.Offer_dbo.ReferenceData_BookTypeId";
ALTER TABLE public."Offer" ADD CONSTRAINT "FK_dbo.Offer_dbo.ReferenceData_BookTypeId" FOREIGN KEY ("BookTypeId") REFERENCES public."ReferenceData" ("Id");

ALTER TABLE public."Offer" DROP CONSTRAINT IF EXISTS "FK_dbo.Offer_dbo.ReferenceData_ConditionId";
ALTER TABLE public."Offer" ADD CONSTRAINT "FK_dbo.Offer_dbo.ReferenceData_ConditionId" FOREIGN KEY ("ConditionId") REFERENCES public."ReferenceData" ("Id");

ALTER TABLE public."Offer" DROP CONSTRAINT IF EXISTS "FK_dbo.Offer_dbo.ReferenceData_GenreId";
ALTER TABLE public."Offer" ADD CONSTRAINT "FK_dbo.Offer_dbo.ReferenceData_GenreId" FOREIGN KEY ("GenreId") REFERENCES public."ReferenceData" ("Id");

ALTER TABLE public."Offer" DROP CONSTRAINT IF EXISTS "FK_dbo.Offer_dbo.ReferenceData_PublisherId";
ALTER TABLE public."Offer" ADD CONSTRAINT "FK_dbo.Offer_dbo.ReferenceData_PublisherId" FOREIGN KEY ("PublisherId") REFERENCES public."ReferenceData" ("Id");

ALTER TABLE public."Order" DROP CONSTRAINT IF EXISTS "FK_dbo.Order_dbo.Address_AddressId";
ALTER TABLE public."Order" ADD CONSTRAINT "FK_dbo.Order_dbo.Address_AddressId" FOREIGN KEY ("AddressId") REFERENCES public."Address" ("Id") ON DELETE CASCADE;

ALTER TABLE public."Order" DROP CONSTRAINT IF EXISTS "FK_dbo.Order_dbo.Customer_CustomerId";
ALTER TABLE public."Order" ADD CONSTRAINT "FK_dbo.Order_dbo.Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customer" ("Id");

ALTER TABLE public."OrderItem" DROP CONSTRAINT IF EXISTS "FK_dbo.OrderItem_dbo.Book_BookId";
ALTER TABLE public."OrderItem" ADD CONSTRAINT "FK_dbo.OrderItem_dbo.Book_BookId" FOREIGN KEY ("BookId") REFERENCES public."Book" ("Id") ON DELETE CASCADE;

ALTER TABLE public."OrderItem" DROP CONSTRAINT IF EXISTS "FK_dbo.OrderItem_dbo.Order_OrderId";
ALTER TABLE public."OrderItem" ADD CONSTRAINT "FK_dbo.OrderItem_dbo.Order_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Order" ("Id") ON DELETE CASCADE;

ALTER TABLE public."ShoppingCartItem" DROP CONSTRAINT IF EXISTS "FK_dbo.ShoppingCartItem_dbo.Book_BookId";
ALTER TABLE public."ShoppingCartItem" ADD CONSTRAINT "FK_dbo.ShoppingCartItem_dbo.Book_BookId" FOREIGN KEY ("BookId") REFERENCES public."Book" ("Id") ON DELETE CASCADE;

ALTER TABLE public."ShoppingCartItem" DROP CONSTRAINT IF EXISTS "FK_dbo.ShoppingCartItem_dbo.ShoppingCart_ShoppingCartId";
ALTER TABLE public."ShoppingCartItem" ADD CONSTRAINT "FK_dbo.ShoppingCartItem_dbo.ShoppingCart_ShoppingCartId" FOREIGN KEY ("ShoppingCartId") REFERENCES public."ShoppingCart" ("Id") ON DELETE CASCADE;

-- Seed data. OVERRIDING SYSTEM VALUE is the PostgreSQL counterpart of
-- SET IDENTITY_INSERT ... ON (dual-db-port §7). Seed reference data first so the
-- Book rows' foreign keys resolve.

INSERT INTO public."ReferenceData" ("Id", "DataType", "Text", "CreatedBy", "CreatedOn", "UpdatedOn")
OVERRIDING SYSTEM VALUE VALUES
(1, 2, 'Hardcover', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(2, 2, 'Trade Paperback', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(3, 2, 'Mass Market Paperback', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(4, 1, 'New', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(5, 1, 'Like New', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(6, 1, 'Good', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(7, 1, 'Acceptable', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(8, 3, 'Biographies', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(9, 3, 'Children''s Books', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(10, 3, 'History', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(11, 3, 'Literature & Fiction', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(12, 3, 'Mystery, Thriller & Suspense', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(13, 3, 'Science Fiction & Fantasy', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(14, 3, 'Travel', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(15, 0, 'Arcadia Books', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(16, 0, 'Astral Publishing', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(17, 0, 'Moonlight Publishing', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(18, 0, 'Dreamscape Press', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(19, 0, 'Enchanted Library', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(20, 0, 'Fantasia House', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(21, 0, 'Horizon Books', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(22, 0, 'Infinity Press', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(23, 0, 'Paradigm Publishing', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340'),
(24, 0, 'Aurora Publishing', 'System', '2024-09-12T02:49:12.340', '2024-09-12T02:49:12.340')
ON CONFLICT ("Id") DO NOTHING;

SELECT setval(pg_get_serial_sequence('public."ReferenceData"', 'Id'), (SELECT MAX("Id") FROM public."ReferenceData"));

INSERT INTO public."Book" ("Id", "Name", "Author", "Year", "ISBN", "PublisherId", "BookTypeId", "GenreId", "ConditionId", "CoverImageUrl", "Summary", "Price", "Quantity", "CreatedBy", "CreatedOn", "UpdatedOn")
OVERRIDING SYSTEM VALUE VALUES
(1, '2020: The Apocalypse', 'Li Juan', NULL, '6556784356', 15, 1, 13, 5, '/Content/Images/coverimages/apocalypse.png', NULL, 10.95::numeric(18,2), 25, 'System', '2024-09-12T02:49:12.353', '2024-09-12T02:49:12.353'),
(2, 'Children Of Iron', 'Nikki Wolf', NULL, '7665438976', 16, 1, 11, 6, '/Content/Images/coverimages/childrenofiron.png', NULL, 13.95::numeric(18,2), 3, 'System', '2024-09-12T02:49:12.353', '2024-09-12T02:49:12.353'),
(3, 'Gold In The Dark', 'Richard Roe', NULL, '5442280765', 17, 1, 13, 5, '/Content/Images/coverimages/goldinthedark.png', NULL, 6.50::numeric(18,2), 10, 'System', '2024-09-12T02:49:12.353', '2024-09-12T02:49:12.353'),
(4, 'Leagues Of Smoke', 'Pat Candella', NULL, '4556789542', 18, 2, 11, 7, '/Content/Images/coverimages/leaguesofsmoke.png', NULL, 3.00::numeric(18,2), 1, 'System', '2024-09-12T02:49:12.353', '2024-09-12T02:49:12.353'),
(5, 'Alone With The Stars', 'Carlos Salazar', NULL, '4563358087', 19, 2, 12, 5, '/Content/Images/coverimages/alonewiththestars.png', NULL, 15.95::numeric(18,2), 5, 'System', '2024-09-12T02:49:12.353', '2024-09-12T02:49:12.353'),
(6, 'The Girl In The Polaroid', 'Terri Whitlock', NULL, '2354435678', 20, 1, 12, 6, '/Content/Images/coverimages/girlinthepolaroid.png', NULL, 8.25::numeric(18,2), 2, 'System', '2024-09-12T02:49:12.353', '2024-09-12T02:49:12.353'),
(7, '1001 Jokes', 'Mary Major', NULL, '6554789632', 21, 2, 11, 5, '/Content/Images/coverimages/1001jokes.png', NULL, 13.95::numeric(18,2), 7, 'System', '2024-09-12T02:49:12.353', '2024-09-12T02:49:12.353'),
(8, 'My Search For Meaning', 'Mateo Jackson', NULL, '4558786554', 22, 3, 8, 7, '/Content/Images/coverimages/mysearchformeaning.png', NULL, 5.00::numeric(18,2), 15, 'System', '2024-09-12T02:49:12.353', '2024-09-12T02:49:12.353')
ON CONFLICT ("Id") DO NOTHING;

SELECT setval(pg_get_serial_sequence('public."Book"', 'Id'), (SELECT MAX("Id") FROM public."Book"));
