-- Bob's Used Books Classic - PostgreSQL 16 schema + seed data.
-- Per-engine translation of bobs-used-bookstore-classic-db.sql (SQL Server), generated by the
-- dual-db-port run against commit 7e3dc2f9. The SQL Server script is unchanged and remains
-- authoritative for SQL Server deployments.
--
-- Mapping decisions (identifier_style = preserve):
--   * Identifiers keep PascalCase and are double-quoted to match the EF6 model.
--   * nvarchar(max) -> text, nvarchar(450) -> varchar(450)
--   * datetime      -> timestamp (without time zone; application stores UTC values)
--   * decimal(18,2) -> numeric(18,2)
--   * bit           -> boolean
--   * int IDENTITY  -> GENERATED BY DEFAULT AS IDENTITY (explicit seed ids allowed)
--   * RowVersion (rowversion) is NOT created: PostgreSQL exposes the auto-updating system
--     column xmin instead; the EF6 PostgreSQL path does not map the concurrency token
--     (see DUAL_DB_PORT_REPORT.md section 8).
--   * __MigrationHistory is omitted: the original script's model blob embeds a SQL Server
--     SSDL and cannot be translated; EF6 creates and maintains its own history table when
--     the database initializer runs.
--   * SQL Server database-level options (compatibility level, full text, broker, filestream,
--     query store, recovery model) have no PostgreSQL equivalent and are omitted.

BEGIN;

CREATE TABLE "Address" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "AddressLine1" text NULL,
    "AddressLine2" text NULL,
    "City"         text NULL,
    "State"        text NULL,
    "Country"      text NULL,
    "ZipCode"      text NULL,
    "CustomerId"   integer NOT NULL,
    "IsActive"     boolean NOT NULL,
    "CreatedBy"    text NULL,
    "CreatedOn"    timestamp NOT NULL,
    "UpdatedOn"    timestamp NOT NULL,
    CONSTRAINT "PK_Address" PRIMARY KEY ("Id")
);

CREATE TABLE "Book" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name"         text NULL,
    "Author"       text NULL,
    "Year"         integer NULL,
    "ISBN"         text NULL,
    "PublisherId"  integer NOT NULL,
    "BookTypeId"   integer NOT NULL,
    "GenreId"      integer NOT NULL,
    "ConditionId"  integer NOT NULL,
    "CoverImageUrl" text NULL,
    "Summary"      text NULL,
    "Price"        numeric(18, 2) NOT NULL,
    "Quantity"     integer NOT NULL,
    "CreatedBy"    text NULL,
    "CreatedOn"    timestamp NOT NULL,
    "UpdatedOn"    timestamp NOT NULL,
    CONSTRAINT "PK_Book" PRIMARY KEY ("Id")
);

CREATE TABLE "Customer" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Sub"         varchar(450) NULL,
    "Username"    text NULL,
    "FirstName"   text NULL,
    "LastName"    text NULL,
    "Email"       text NULL,
    "DateOfBirth" timestamp NULL,
    "Phone"       text NULL,
    "CreatedBy"   text NULL,
    "CreatedOn"   timestamp NOT NULL,
    "UpdatedOn"   timestamp NOT NULL,
    CONSTRAINT "PK_Customer" PRIMARY KEY ("Id")
);

CREATE TABLE "Offer" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Author"      text NULL,
    "ISBN"        text NULL,
    "BookName"    text NULL,
    "FrontUrl"    text NULL,
    "GenreId"     integer NOT NULL,
    "ConditionId" integer NOT NULL,
    "PublisherId" integer NOT NULL,
    "BookTypeId"  integer NOT NULL,
    "Summary"     text NULL,
    "OfferStatus" integer NOT NULL,
    "Comment"     text NULL,
    "CustomerId"  integer NOT NULL,
    "BookPrice"   numeric(18, 2) NOT NULL,
    "CreatedBy"   text NULL,
    "CreatedOn"   timestamp NOT NULL,
    "UpdatedOn"   timestamp NOT NULL,
    CONSTRAINT "PK_Offer" PRIMARY KEY ("Id")
);

CREATE TABLE "Order" (
    "Id"           integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CustomerId"   integer NOT NULL,
    "AddressId"    integer NOT NULL,
    "DeliveryDate" timestamp NOT NULL,
    "OrderStatus"  integer NOT NULL,
    "CreatedBy"    text NULL,
    "CreatedOn"    timestamp NOT NULL,
    "UpdatedOn"    timestamp NOT NULL,
    CONSTRAINT "PK_Order" PRIMARY KEY ("Id")
);

CREATE TABLE "OrderItem" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrderId"   integer NOT NULL,
    "BookId"    integer NOT NULL,
    "Quantity"  integer NOT NULL,
    "CreatedBy" text NULL,
    "CreatedOn" timestamp NOT NULL,
    "UpdatedOn" timestamp NOT NULL,
    CONSTRAINT "PK_OrderItem" PRIMARY KEY ("Id")
);

CREATE TABLE "ReferenceData" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "DataType"  integer NOT NULL,
    "Text"      text NULL,
    "CreatedBy" text NULL,
    "CreatedOn" timestamp NOT NULL,
    "UpdatedOn" timestamp NOT NULL,
    CONSTRAINT "PK_ReferenceData" PRIMARY KEY ("Id")
);

CREATE TABLE "ShoppingCart" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CorrelationId" text NULL,
    "CreatedBy"     text NULL,
    "CreatedOn"     timestamp NOT NULL,
    "UpdatedOn"     timestamp NOT NULL,
    CONSTRAINT "PK_ShoppingCart" PRIMARY KEY ("Id")
);

CREATE TABLE "ShoppingCartItem" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ShoppingCartId" integer NOT NULL,
    "BookId"        integer NOT NULL,
    "Quantity"      integer NOT NULL,
    "WantToBuy"     boolean NOT NULL,
    "CreatedBy"     text NULL,
    "CreatedOn"     timestamp NOT NULL,
    "UpdatedOn"     timestamp NOT NULL,
    CONSTRAINT "PK_ShoppingCartItem" PRIMARY KEY ("Id", "ShoppingCartId")
);

-- Seed data (mirrors the SQL Server script; identity override is permitted by
-- GENERATED BY DEFAULT AS IDENTITY).

INSERT INTO "ReferenceData" ("Id", "DataType", "Text", "CreatedBy", "CreatedOn", "UpdatedOn") VALUES
    (1, 2, 'Hardcover', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (2, 2, 'Trade Paperback', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (3, 2, 'Mass Market Paperback', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (4, 1, 'New', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (5, 1, 'Like New', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (6, 1, 'Good', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (7, 1, 'Acceptable', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (8, 3, 'Biographies', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (9, 3, 'Children''s Books', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (10, 3, 'History', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (11, 3, 'Literature & Fiction', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (12, 3, 'Mystery, Thriller & Suspense', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (13, 3, 'Science Fiction & Fantasy', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (14, 3, 'Travel', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (15, 0, 'Arcadia Books', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (16, 0, 'Astral Publishing', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (17, 0, 'Moonlight Publishing', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (18, 0, 'Dreamscape Press', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (19, 0, 'Enchanted Library', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (20, 0, 'Fantasia House', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (21, 0, 'Horizon Books', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (22, 0, 'Infinity Press', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (23, 0, 'Paradigm Publishing', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340'),
    (24, 0, 'Aurora Publishing', 'System', '2024-09-12 02:49:12.340', '2024-09-12 02:49:12.340');

INSERT INTO "Book" ("Id", "Name", "Author", "Year", "ISBN", "PublisherId", "BookTypeId", "GenreId", "ConditionId", "CoverImageUrl", "Summary", "Price", "Quantity", "CreatedBy", "CreatedOn", "UpdatedOn") VALUES
    (1, '2020: The Apocalypse', 'Li Juan', NULL, '6556784356', 15, 1, 13, 5, '/Content/Images/coverimages/apocalypse.png', NULL, 10.95, 25, 'System', '2024-09-12 02:49:12.353', '2024-09-12 02:49:12.353'),
    (2, 'Children Of Iron', 'Nikki Wolf', NULL, '7665438976', 16, 1, 11, 6, '/Content/Images/coverimages/childrenofiron.png', NULL, 13.95, 3, 'System', '2024-09-12 02:49:12.353', '2024-09-12 02:49:12.353'),
    (3, 'Gold In The Dark', 'Richard Roe', NULL, '5442280765', 17, 1, 13, 5, '/Content/Images/coverimages/goldinthedark.png', NULL, 6.50, 10, 'System', '2024-09-12 02:49:12.353', '2024-09-12 02:49:12.353'),
    (4, 'Leagues Of Smoke', 'Pat Candella', NULL, '4556789542', 18, 2, 11, 7, '/Content/Images/coverimages/leaguesofsmoke.png', NULL, 3.00, 1, 'System', '2024-09-12 02:49:12.353', '2024-09-12 02:49:12.353'),
    (5, 'Alone With The Stars', 'Carlos Salazar', NULL, '4563358087', 19, 2, 12, 5, '/Content/Images/coverimages/alonewiththestars.png', NULL, 15.95, 5, 'System', '2024-09-12 02:49:12.353', '2024-09-12 02:49:12.353'),
    (6, 'The Girl In The Polaroid', 'Terri Whitlock', NULL, '2354435678', 20, 1, 12, 6, '/Content/Images/coverimages/girlinthepolaroid.png', NULL, 8.25, 2, 'System', '2024-09-12 02:49:12.353', '2024-09-12 02:49:12.353'),
    (7, '1001 Jokes', 'Mary Major', NULL, '6554789632', 21, 2, 11, 5, '/Content/Images/coverimages/1001jokes.png', NULL, 13.95, 7, 'System', '2024-09-12 02:49:12.353', '2024-09-12 02:49:12.353'),
    (8, 'My Search For Meaning', 'Mateo Jackson', NULL, '4558786554', 22, 3, 8, 7, '/Content/Images/coverimages/mysearchformeaning.png', NULL, 5.00, 15, 'System', '2024-09-12 02:49:12.353', '2024-09-12 02:49:12.353');

-- Re-sync identity sequences above the seeded ids (runbook: required after any
-- explicit-id seed insert so the next application-generated id does not collide).
SELECT setval(pg_get_serial_sequence('"Book"', 'Id'), (SELECT MAX("Id") FROM "Book"));
SELECT setval(pg_get_serial_sequence('"ReferenceData"', 'Id'), (SELECT MAX("Id") FROM "ReferenceData"));

-- Indexes (same shapes and names as the SQL Server script, without clustered/storage options).

CREATE INDEX "IX_CustomerId" ON "Address" ("CustomerId");

CREATE INDEX "IX_BookTypeId" ON "Book" ("BookTypeId");
CREATE INDEX "IX_ConditionId" ON "Book" ("ConditionId");
CREATE INDEX "IX_GenreId" ON "Book" ("GenreId");
CREATE INDEX "IX_PublisherId" ON "Book" ("PublisherId");

CREATE UNIQUE INDEX "IX_Sub" ON "Customer" ("Sub");

CREATE INDEX "IX_BookTypeId" ON "Offer" ("BookTypeId");
CREATE INDEX "IX_ConditionId" ON "Offer" ("ConditionId");
CREATE INDEX "IX_CustomerId" ON "Offer" ("CustomerId");
CREATE INDEX "IX_GenreId" ON "Offer" ("GenreId");
CREATE INDEX "IX_PublisherId" ON "Offer" ("PublisherId");

CREATE INDEX "IX_AddressId" ON "Order" ("AddressId");
CREATE INDEX "IX_CustomerId" ON "Order" ("CustomerId");

CREATE INDEX "IX_BookId" ON "OrderItem" ("BookId");
CREATE INDEX "IX_OrderId" ON "OrderItem" ("OrderId");

CREATE INDEX "IX_BookId" ON "ShoppingCartItem" ("BookId");
CREATE INDEX "IX_ShoppingCartId" ON "ShoppingCartItem" ("ShoppingCartId");

-- Foreign keys (same delete rules as the SQL Server script).

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Customer_CustomerId" FOREIGN KEY ("CustomerId")
    REFERENCES "Customer" ("Id") ON DELETE CASCADE;

ALTER TABLE "Book" ADD CONSTRAINT "FK_Book_ReferenceData_BookTypeId" FOREIGN KEY ("BookTypeId")
    REFERENCES "ReferenceData" ("Id");
ALTER TABLE "Book" ADD CONSTRAINT "FK_Book_ReferenceData_ConditionId" FOREIGN KEY ("ConditionId")
    REFERENCES "ReferenceData" ("Id");
ALTER TABLE "Book" ADD CONSTRAINT "FK_Book_ReferenceData_GenreId" FOREIGN KEY ("GenreId")
    REFERENCES "ReferenceData" ("Id");
ALTER TABLE "Book" ADD CONSTRAINT "FK_Book_ReferenceData_PublisherId" FOREIGN KEY ("PublisherId")
    REFERENCES "ReferenceData" ("Id");

ALTER TABLE "Offer" ADD CONSTRAINT "FK_Offer_Customer_CustomerId" FOREIGN KEY ("CustomerId")
    REFERENCES "Customer" ("Id") ON DELETE CASCADE;
ALTER TABLE "Offer" ADD CONSTRAINT "FK_Offer_ReferenceData_BookTypeId" FOREIGN KEY ("BookTypeId")
    REFERENCES "ReferenceData" ("Id");
ALTER TABLE "Offer" ADD CONSTRAINT "FK_Offer_ReferenceData_ConditionId" FOREIGN KEY ("ConditionId")
    REFERENCES "ReferenceData" ("Id");
ALTER TABLE "Offer" ADD CONSTRAINT "FK_Offer_ReferenceData_GenreId" FOREIGN KEY ("GenreId")
    REFERENCES "ReferenceData" ("Id");
ALTER TABLE "Offer" ADD CONSTRAINT "FK_Offer_ReferenceData_PublisherId" FOREIGN KEY ("PublisherId")
    REFERENCES "ReferenceData" ("Id");

ALTER TABLE "Order" ADD CONSTRAINT "FK_Order_Address_AddressId" FOREIGN KEY ("AddressId")
    REFERENCES "Address" ("Id") ON DELETE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "FK_Order_Customer_CustomerId" FOREIGN KEY ("CustomerId")
    REFERENCES "Customer" ("Id");

ALTER TABLE "OrderItem" ADD CONSTRAINT "FK_OrderItem_Book_BookId" FOREIGN KEY ("BookId")
    REFERENCES "Book" ("Id") ON DELETE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "FK_OrderItem_Order_OrderId" FOREIGN KEY ("OrderId")
    REFERENCES "Order" ("Id") ON DELETE CASCADE;

ALTER TABLE "ShoppingCartItem" ADD CONSTRAINT "FK_ShoppingCartItem_Book_BookId" FOREIGN KEY ("BookId")
    REFERENCES "Book" ("Id") ON DELETE CASCADE;
ALTER TABLE "ShoppingCartItem" ADD CONSTRAINT "FK_ShoppingCartItem_ShoppingCart_ShoppingCartId" FOREIGN KEY ("ShoppingCartId")
    REFERENCES "ShoppingCart" ("Id") ON DELETE CASCADE;

COMMIT;
